/* Generated by scripts/vendor-minimal-react-template.cjs — template: antd-less */
const path = require('path')
const { createAntdLessWebviewWebpackConfig } = require('./bundler/webpack.factory.js')

const context = path.resolve(__dirname, '..')
const templateRoot = path.resolve(__dirname, 'bundler')

const baseFactory = createAntdLessWebviewWebpackConfig({
  context,
  entry: path.resolve(context, 'src/webview/index.tsx'),
  htmlTemplate: path.resolve(templateRoot, 'src/index.html'),
  favicon: path.resolve(templateRoot, 'src/favicon.ico'),
  babelConfig: path.resolve(context, '.babelrc')
})

// Wrap factory to inject aliases for ESM-only packages that webpack 5 picks over CJS.
module.exports = (env, argv) => {
  const config = baseFactory(env, argv)
  config.resolve = config.resolve ?? {}
  config.resolve.alias = {
    ...config.resolve.alias,
    // Ensure a single React runtime even when aliasing to external local package dist.
    react: path.resolve(context, 'node_modules/react'),
    'react-dom': path.resolve(context, 'node_modules/react-dom'),
    'react/jsx-runtime': path.resolve(context, 'node_modules/react/jsx-runtime'),
    'react/jsx-dev-runtime': path.resolve(context, 'node_modules/react/jsx-dev-runtime'),
    // right-image-preview publishes ESM as the "import" condition which webpack 5 (target:web) prefers.
    // Force the CJS build to avoid ESM strict-path resolution issues with react/jsx-runtime.
    'right-image-preview': path.resolve(context, 'node_modules/right-image-preview/dist/index.cjs')
  }
  return config
}
